### ISSUE TITLE
[Question] Pattern Distortion

### ISSUE THREAD

**Issue by Voxel-Friend** [TheIllusiveC4/Bedspreads#1]
Is there any chance for you to address the fact that banner patterns get squashed due to the dimensions of the display area of the bed? Not horribly worried about it, though it would be nice for the pattern to more accurately transfer to the bed.

**Comment by TheIllusiveC4** [comment]
Can you go into more detail along with some screenshots? The thing about this is that it's not like I'm applying the banner patterns directly onto the bed. The bed patterns are unique textures by me that simply follow the banner design as closely as possible given the bed texture's dimension constraints. So what you're really asking me is to just "make the bed banner textures different". Which is reasonable, of course, it's just that I'll need more specifics to go on.

**Comment by Voxel-Friend** [comment]
Sure, here is what I mean:
![2018-12-15_23 04 08](https://user-images.githubusercontent.com/12395262/50050407-aba54780-00bf-11e9-8bd8-05dc0aef34cf.png)
As you can see, the detail seen in the bed version is significantly different than what is shown in the banner.
I can understand technical limitations, so if it is not something easily fixed, don't sweat it.

**Comment by TheIllusiveC4** [comment]
Hm, yeah, I definitely see what you mean. Unfortunately, that's just how it is since the dimensions aren't the same between the bed and the banner texture. 

It's one thing if the textures just weren't good, you know, I can always try and make better textures. But if it's about banner-to-bed designs not matching, that's just an unfortunate result of their incompatible sizes. The more complicated the design, the worse the difference will be, since each design has very small variations to accommodate for the differences.

As an example, I'll talk about the flower design within the screenshot you presented. The banner's flower design is 18 pixels wide. The entire workable area of the bed is only 16 pixels. So designs had to be made different out of necessity. 

You'll see some of the same disparities, although in different ways, when transferring banners to shields in vanilla Minecraft.

Sorry if that got a little long-winded, just wanted to make sure my explanation was sufficiently thorough.

Also, very cool banner design.

**Comment by Voxel-Friend** [comment]
Yeah, I figured it was something along these lines, I just figured I should bring it up in case it was unintentional functionality. It's something I could probably get over. For that matter it's just another set of patterns I can use to design neat bed designs on. Thank you for your time!
